apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - image: chillingspree/do-course:1
          name: test-container
          ports:
            - containerPort: 8080